name = "project-verification"
version = "0.1.0"
defaultTargets = ["project-verification"]
moreLinkArgs = [
    "-L./../build",
    "-lexample_lib",
    "-Wl,-rpath,./../build"
]
precompileModules = true
supportInterpreter = true

[[lean_lib]]
name = "ProjectVerification"

[[lean_exe]]
name = "project-verification"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
revision = "stable"

[[require]]
name = "plausible"
scope = "leanprover-community"
revision = "stable"